OnlineCoursesReservation/Areas/Admin/Controllers/FaqsController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineCoursesReservation_DataAccess.Models;
using OnlineCoursesReservation_DataAccess.Services.Repositories;

namespace OnlineCoursesReservation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FaqsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public FaqsController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public async Task<ActionResult> Index()
        {
            return View(await unitOfWork.FaqRepositoy.GetAllAsync());
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FAQ model)
        {
            try
            {

                if (!ModelState.IsValid)
                {
                    return View("Index", await unitOfWork.FaqRepositoy.GetAllAsync());
                }

                await unitOfWork.FaqRepositoy.Add(model);
                await unitOfWork.ComplateAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return BadRequest();
            }
        }


        public async Task<ActionResult> Edit(int id)
        {
            return View(await unitOfWork.FaqRepositoy.GetByIdAsync(id));
        }

        // POST: FaqsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(FAQ fAQ)
        {
            try
            {


                if (!ModelState.IsValid)
                {
                    return View(fAQ);
                }

                var result = await unitOfWork.FaqRepositoy.Update(fAQ);
                if (!result)
                {

                    return BadRequest();
                }

                await unitOfWork.ComplateAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return Problem();
            }
        }



        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                var item = await unitOfWork.FaqRepositoy.GetByIdAsync(id);
                if (item == null)
                    return NotFound();

                var result = await unitOfWork.FaqRepositoy.Delete(item);
                if (!result)
                    return BadRequest();

                await unitOfWork.ComplateAsync();
                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

OnlineCoursesReservation/Areas/Admin/Controllers/RolesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineCoursesReservation.Areas.Admin.ViewModels;

namespace OnlineCoursesReservation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        // GET: RolesController
        public async Task<ActionResult> Index()
        {
            return View(await roleManager.Roles.ToListAsync());
        }



        // POST: RolesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RoleFormViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Index", await roleManager.Roles.ToListAsync());
                }

                if (roleManager.RoleExistsAsync(model.Name).Result)
                {
                    ModelState.AddModelError("Name", "الدور موجود!");
                    return View("Index", await roleManager.Roles.ToListAsync());
                }

                await roleManager.CreateAsync(new IdentityRole(model.Name.Trim()));

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return Problem();
            }
        }

        // GET: RolesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RolesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }



        // POST: RolesController/Delete/5
        [HttpDelete]
        public async Task<ActionResult> Delete(string id)
        {
            try
            {
                if (id == null)
                {
                    return BadRequest();
                }

                var role = await roleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return NotFound();
                }

                await roleManager.DeleteAsync(role);

                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

OnlineCoursesReservation/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OnlineCoursesReservation.Areas.Admin.ViewModels;
using OnlineCoursesReservation.Models;

namespace OnlineCoursesReservation.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<ApplicationUser> roleManager;

        public UsersController(UserManager<ApplicationUser> userManager)
        {
            this.userManager = userManager;
        }

        // GET: UsersController
        public async Task<ActionResult> Index()
        {
            var users = await userManager.Users.Select(user => new UserViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                UserName = user.UserName,
                Email = user.Email,
                Roles = userManager.GetRolesAsync(user).Result.ToList()
            }).ToListAsync();

            return View(users);
        }

        // GET: UsersController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UsersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UsersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: UsersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UsersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: UsersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineCoursesReservation/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;

namespace OnlineCoursesReservation.Controllers
{
    public class CoursesController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //[HttpPost]
        //public IActionResult FilterCourses(int priceRange, string certificate)
        //{
        //    var filteredCourses = _context.Courses.AsQueryable();

        //    // Parse price range
        //    if (!string.IsNullOrEmpty(priceRange))
        //    {
        //        var priceLimits = priceRange.Split('-').Select(decimal.Parse).ToList();
        //        var minPrice = priceLimits[0];
        //        var maxPrice = priceLimits[1];
        //        filteredCourses = filteredCourses.Where(c => c.Price >= minPrice && c.Price <= maxPrice);
        //    }

        //    // Parse certificate
        //    if (!string.IsNullOrEmpty(certificate))
        //    {
        //        var hasCertificate = bool.Parse(certificate);
        //        filteredCourses = filteredCourses.Where(c => c.HasCertificate == hasCertificate);
        //    }

        //    var filteredCourseList = filteredCourses.ToList();

        //    return PartialView("_CourseListPartial", filteredCourseList);
        //}

    }
}

OnlineCoursesReservation/Areas/Admin/Views/_AdminLayout.cshtml
@{
    var action = ViewContext.RouteData.Values["action"].ToString();
    var controller = ViewContext.RouteData.Values["controller"].ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> لوحه التحكم  | @ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="~/imgs/WhatsApp Image 2024-02-04 at 11.31.47 AM(1).jpeg">


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/lib/aos/aos.css">
    <link rel="stylesheet" href="~/lib/apexcharts/apexcharts.css">
    <link rel="stylesheet" href="~/OnlineCoursesReservation.styles.css" asp-append-version="true" />
    <link href="~/lib/quill/quill.snow.css" rel="stylesheet" />
    <!-- Remix Icons -->
    <link rel="stylesheet" href="~/lib/remixicon/remixicon.css">

    <!-- google font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;500;600;700;800;900;1000&display=swap" rel="stylesheet">

    <style>
            :root{
        --text-slate:#0f172a;
        --text-indego:#4338ca;
        }

        *{
            font-family: 'cairo','sans-serf';
        }

        .text-slate{
            color: var(--text-slate);
        }

        section{
            min-height: 100vdh;
        }
        .active-link{
            font-weight: bold;
        }
        .navbar-nav a{
            font-size: 1.1rem;
            color: #000;
        }
        .navbar nav a:hover{
            color: #00000089;
        }

        /* card */

        .info-card:hover {
            transition: 500ms;
            box-shadow: 10px 10px 20px #0000001a;
        }
        /* card */
    </style>

</head>
<body dir="rtl">


    <!-- بداية قسم شريط التنقل -->
    <div class="container">

        <nav class="navbar navbar-expand-lg">
            <div class="container">


                <div class="mx-4">
                    <a class="navbar-brand text-dark fw-bold fs-1 " asp-action="Index" asp-controller="Home" asp-area="Admin">لوحة التحكم</a>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="تبديل التنقل">
                    <span class="navbar-toggler-icon"><i class="fa-solid fa-bars"></i></span>
                </button>


                <div class="collapse navbar-collapse justify-content-between" id="navbarNavAltMarkup">

                    <div class="navbar-nav ms-5">
                        <a asp-action="Index" asp-controller="Home"         class="nav-link @(controller == "Home" && action == "Index" ? "active-link" : "") "> عام</a>
                        <a asp-action="Index" asp-controller="Users"        class="nav-link @(controller == "Users" && action=="Index" ? "active-link" : "" )">المستخدمين</a>
                        <a asp-action="Index" asp-controller="Courses"      class="nav-link @(controller == "Courses" && action=="Index" ? "active-link" : "" )">الدورات</a>
                        <a asp-action="Index" asp-controller="Reservations" class="nav-link @(controller == "Reservations" && action=="Index" ? "active-link" : "" )">الحجوزات</a>
                        <a asp-action="Index" asp-controller="Teachers"     class="nav-link @(controller == "Teachers" && action=="Index" ? "active-link" : "" )">المدرسين</a>
                        <a asp-action="Index" asp-controller="Categories"   class="nav-link @(controller == "Categories" && action=="Index" ? "active-link" : "" )">الفئات</a>
                        <a asp-action="Index" asp-controller="Levels"       class="nav-link @(controller == "Levels" && action=="Index" ? "active-link" : "" )">المستويات</a>
                        <a asp-action="Index" asp-controller="Faqs"         class="nav-link @(controller == "Faqs" && action=="Index" ? "active-link" : "" )">FAQs</a>
                        <a asp-action="Index" asp-controller="Roles"        class="nav-link @(controller == "Roles" && action=="Index" ? "active-link" : "" )">Roles</a>
                     
                     
                        

                    </div> 
                    <div>
                        <partial name="_LoginPartial"></partial>
                    </div>
                </div>




            </div>
        </nav>
    </div>
    <!-- نهاية قسم شريط التنقل -->

    <main role="main" class="container p-5">
       

        @RenderBody()
    </main>


    
    <script src="~/lib/aos/aos.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/apexcharts/apexcharts.js"></script>    
    <script src="~/lib/quill/quill.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>